# Generated by Django 5.2.7 on 2025-10-03 09:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'images',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(choices=[('RegNetY320', 'RegNetY320'), ('VGG16', 'VGG16')], max_length=50)),
                ('prediction', models.CharField(choices=[('Cancer', 'Cancer'), ('Non-Cancer', 'Non-Cancer')], max_length=50)),
                ('confidence_score', models.FloatField(help_text='Confidence score (0-1)')),
                ('processing_time', models.FloatField(help_text='Processing time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_results', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_results', to='detection.image')),
            ],
            options={
                'verbose_name': 'Detection Result',
                'verbose_name_plural': 'Detection Results',
                'db_table': 'detection_results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['prediction', 'created_at'], name='detection_r_predict_ba24fa_idx'), models.Index(fields=['user', 'created_at'], name='detection_r_user_id_54574f_idx')],
            },
        ),
    ]
